# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea8496478a6bde7a04d1d470af5084d2f2ba1a515ba961ce84383be87a9835cf45a2d49a1498f70406f3528419b4cfd46205b8826343e4974ced4e3e0d6863e4
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>

test:
  secret_key_base: 001e823984cef0ec81f2825b26bd90b0053677beb14fdc34370cf4a2a32cd174421cfb41c4a04b0c46b7b85c32bea4f65054586b717a25cc5ce551401d4f7951

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
